version: '3'

services:
  frontend:
    build: ./docker/frontend/Dockerfile
    # map port 8080 from host to 8080 in container
    ports: 8080:8080

  backend:
    build: ./docker/backend/Dockerfile
    # map port 8081 from host to 8081 in container
    ports: 8081:8081