name: Build and Deploy

on:
  push:
    branches:
      - NickAhn/ci-cd

env:
  applicationfolder: /

jobs:
  test:
    name: Verify github secrets are set
    runs-on: ubuntu-latest
    steps:
      - name: Print start message
        run: echo "Starting test"

      - name: Check for github secrets
        run: |
          secrets=(
            ${{ secrets.AWS_REGION }}
            ${{ secrets.AWS_ACCESS_KEY_ID }}
            ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            ${{ secrets.AWS_SAGEMAKER_ENDPOINT }}
          )

          for secret in "$secrets[@]"; do
            if [[ -z "${{ secrets.AWS_REGION }}" ]]; then
              echo "Missing github secrets"
              exit 1
            fi
          done
      
  deploy:
    needs: test
    name: Build and Deploy 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #aws-region: ${{ secrets.AWS_REGION }}
          aws-region: us-west-1

      - name: Deploy repo with AWS CodeDeploy
        run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment \
              --application-name nexus-ai-app \
              --deployment-group-name nexus-ai-DplGrp \
              --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash \
              --ignore-application-stop-failures \
              --region us-west-1

