name: Build and Deploy

on:
  push:
    branches:
      - NickAhn/ci-cd

env:
  applicationfolder: /
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  test:
    name: test workflow initialization
    runs-on: ubuntu-latest
    steps:
      - name: Print start message
        run: echo "Starting test"

      - name: Check env vars
        run: |
          if [[ -z "${{ secrets.AWS_REGION }}" ]]; then
            echo "AWS_REGION is not set"
            exit 1
          else
            echo "AWS_REGION is set"
          fi
      
  deploy:
    needs: test
    name: Build and Deploy 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Deploy repo with AWS CodeDeploy
        run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment \
              --application-name nexus-ai-app \
              --deployment-group-name nexus-ai-DprGrp \
              --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash \
              --ignore-application-stop-failures \
              --region $AWS_REGION

